# Generated by Django 5.0.4 on 2024-04-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_alter_institution_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[(1, 'Fundacja'), (2, 'Organizacja pozarządowa'), (3, 'Zbiórka lokalna')], default=1, max_length=1),
        ),
    ]
