# Generated by Django 5.0.4 on 2024-04-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_alter_institution_name_alter_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='categories',
            field=models.ManyToManyField(to='charity.category'),
        ),
    ]
